// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj98Q2h51308jKtRuEZZJllUnaPd76A_o',
    appId: '1:41691032548:web:768e5c9a8bda83c0a535f1',
    messagingSenderId: '41691032548',
    projectId: 'skycast-weather-26cc4',
    authDomain: 'skycast-weather-26cc4.firebaseapp.com',
    storageBucket: 'skycast-weather-26cc4.firebasestorage.app',
    measurementId: 'G-VDJXD25PP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBu74510iFqRCQmIol0dPPombeu4HolOY',
    appId: '1:41691032548:android:3f8151f8178fab69a535f1',
    messagingSenderId: '41691032548',
    projectId: 'skycast-weather-26cc4',
    storageBucket: 'skycast-weather-26cc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3UjWt5V9RLIr15RkozTRa1Avi8L7dyI',
    appId: '1:41691032548:ios:b2ba5962c425d13aa535f1',
    messagingSenderId: '41691032548',
    projectId: 'skycast-weather-26cc4',
    storageBucket: 'skycast-weather-26cc4.firebasestorage.app',
    iosBundleId: 'com.skycw.skyCast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3UjWt5V9RLIr15RkozTRa1Avi8L7dyI',
    appId: '1:41691032548:ios:b2ba5962c425d13aa535f1',
    messagingSenderId: '41691032548',
    projectId: 'skycast-weather-26cc4',
    storageBucket: 'skycast-weather-26cc4.firebasestorage.app',
    iosBundleId: 'com.skycw.skyCast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj98Q2h51308jKtRuEZZJllUnaPd76A_o',
    appId: '1:41691032548:web:02bfed472c37a9baa535f1',
    messagingSenderId: '41691032548',
    projectId: 'skycast-weather-26cc4',
    authDomain: 'skycast-weather-26cc4.firebaseapp.com',
    storageBucket: 'skycast-weather-26cc4.firebasestorage.app',
    measurementId: 'G-ZB0CY3KX7P',
  );
}
